include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

variables:
  SSH_USER: $DEPLOY_USER
  SSH_HOST: $DEPLOY_HOST
  SSH_PRIVATE_KEY: $DEPLOY_KEY

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master
  variables:
    DOCKERFILE_PATH: Dockerfile
    CONTEXT: $CI_PROJECT_DIR

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .rules-master
  variables:
    OPT_DOCKER: "-p 80:3000"